version: '3.8'
services:
  # Base de datos compartida para la PoC (en prod serían separadas)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: forjauser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forjaerp
    ports:
      - "5432:5432"

  # Event Bus
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # Servicio de Ventas
  sales-service:
    build: ./sales-service
    ports:
      - "8081:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/forjaerp
    depends_on:
      - rabbitmq
      - postgres

  # Servicio de Producción
  production-service:
    build: ./production-service
    ports:
      - "8082:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq